### ISSUE TITLE
несовместимость библиотек GyverPortal и GyverBus

### ISSUE THREAD

**Issue by alex100dm** [GyverLibs/GyverBus#2]
На сколько я понял одинаковое название функций min. Как это решить если не править самоу либу не знаю

In file included from c:\Users\tlen\Documents\Arduino\libraries\GyverPortal\src/GyverPortal.h:56,
c:\Users\tlen\Documents\Arduino\libraries\GyverPortal\src/objects.h:180:30: error: macro "min" requires 2 arguments, but only 1 given
  180 |     name(n), value(v), min(mn), max(mx), step(stp), decimals(dec), style(st), width(w), disabled(dis) {}
      |                              ^
In file included from c:\Users\tlen\Documents\Arduino\libraries\GyverBus-main\src/GBUS.h:3,
c:\Users\tlen\Documents\Arduino\libraries\GyverBus-main\src/GyverBus.h:128: note: macro "min" defined here
  128 | #define min(a,b) ((a)<(b)?(a):(b))
      |

**Comment by GyverLibs** [comment]
поправил
